# Generated by Django 3.2.8 on 2021-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=31, null=True)),
                ('prenom', models.CharField(max_length=31)),
                ('mail', models.CharField(max_length=31)),
                ('mdp', models.CharField(max_length=31)),
            ],
        ),
    ]
