# Generated by Django 3.2.9 on 2021-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(max_length=2048)),
                ('tmdb_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=31)),
                ('prenom', models.CharField(max_length=31)),
                ('mail', models.CharField(max_length=31, unique=True)),
                ('mdp', models.CharField(max_length=31)),
                ('watch_list', models.ManyToManyField(blank=True, to='api.Content')),
            ],
        ),
    ]
